title: "Carlos Herrera Vázquez"
tagline: "PhD Researcher in Applied Mathematics"
description: "Tensor decomposition & computational mathematics applied to power systems."
remote_theme: jekyll/minima

# Plugins necesarios para SEO y Sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Configuración del diseño
minima:
  skin: dark # Esto activa el modo oscuro elegante
  social_links:
    - { platform: github, user: Lentejas1 }
    # Añade aquí tus otros links si quieres:
    # - { platform: linkedin, user: tu_usuario }

# URLs limpias (sin .html)
permalink: /:title/
markdown: kramdown
highlighter: rouge
